const Data={
    product:[ {
        _id: '1',
        name: 'ShellFort Cat',
        category: 'Cats',
        image: './Images/cat1.jpeg',
        price: 110,
        Rating: 4.5,
        numReviews: 10,
        description: 'Trained cat and very Friendly',
    },
    {
        _id: '2',
        name: 'Dog',
        category: 'Dogs',
        image: './Images/dog1.jpeg',
        price: 240,
        Rating: 4.9,
        numReviews: 7,
        description: 'Trained dog and very Friendly also we loves him and he also.',
    },
    {
        _id: '3',
        name: 'Puppy',
        category: 'Dogs',
        image: './Images/dogs/dog2.jpg',
        price: 190,
        Rating: 4.7,
        numReviews:11,
        description: 'Trained dog and very Friendly',
    },
    {
        _id: '4',
        name: 'Rabit',
        category: 'Rabits',
        image: './Images/rabbit/4390.jpg',
        price: 78,
        Rating: 4.6,
        numReviews:3,
        description: 'Trained Rabbit and very Friendly',
    },
    {
        _id: '5',
        name: 'Jelly Fish',
        category: 'Fishes',
        image: './Images/fish1.jpeg',
        price:30,
        Rating:4.8,
        numReviews:12,
        description: 'Trained Fish and very Friendly',
    },
    {
        _id: '6',
        name: 'Cat',
        category: 'Cats',
        image: './Images/cats/cat1.jpg',
        price:100,
        Rating: 4.4,
        numReviews: 10,
        description: 'Trained cat and very Friendly',
    },
    {
        _id: '7',
        name: 'cock Hen',
        category: 'Cock',
        image: './Images/birds/cock2.jpg',
        price:120,
        Rating: 4.9,
        numReviews:7,
        description: 'Trained dog and very Friendly',
    },
    {
        _id: '8',
        name: 'Cock',
        category: 'Cocks',
        image: './Images/birds/cock1.jpg',
        price:50,
        Rating:4.8,
        numReviews:20,
        description: 'Trained Cock and fighter',
    },
    ],
}

export default Data;